### ISSUE TITLE
Ghost mode not working

### ISSUE THREAD

**Issue by Hayvosh** [nekiro/TFS-1.5-Downgrades#101]
**Protocol version**
7.72

**Describe the bug**
Running the /ghost command as GOD with the default talkaction script from this release crashes the client.

**To Reproduce**
1. Login to the game with a character with GOD status
2. Type the /ghost command

**Expected behavior**
The expected behaviour is to make the character to invisible

**Screenshots**
![image](https://user-images.githubusercontent.com/385028/150598200-9553a595-b2d8-40dc-8ef8-643e41ccbd27.png)

**Additional context**
To get around the issue you can replace these lines :

`		position:sendMagicEffect(CONST_ME_YALAHARIGHOST)`
with
`		position:sendMagicEffect(CONST_ME_MAGIC_BLUE)`

And also remove the line 20
`		position:sendMagicEffect(CONST_ME_SMOKE)`

Doing this makes the ghost spell work, but there is still another bug that comes into play then.
If you logout near another player while still in ghost mode, it will trigger a client crash for the other player.
Giving this error : 
![image](https://user-images.githubusercontent.com/385028/150598490-07984f00-591e-4e94-b43f-675423e4fcdb.png)

This has been tested a few times, and it always trigger a client crash when you logout while in ghost.

**Comment by waqmaz93** [comment]
Confirmed. Lggin out while being in a ghost mode crashes clients for all surrounding players

**Comment by Roddett** [comment]
Found the issue

Add this
```
 if (!player->canSeeCreature(creature))
	continue;
```

Here: https://github.com/nekiro/TFS-1.5-Downgrades/blob/8.60/src/game.cpp#L573

**Comment by Hayvosh** [comment]
> 

Like this?

`	//send to client
	size_t i = 0;
	for (Creature* spectator : spectators) {
		if (!player->canSeeCreature(creature))
			continue;
		if (Player* player = spectator->getPlayer()) {
			player->sendRemoveTileCreature(creature, tilePosition, oldStackPosVector[i++]);
		}
	}`

**Comment by Hayvosh** [comment]
Tried it per my suggestion above, but I get an error while compiling.

"Identifier "player" is undefined" and "'player': undeclared identifier

**Comment by nekiro** [comment]
Closed via #106 though, seems there are still problems.
