### ISSUE TITLE
Blessing bug

### ISSUE THREAD

**Issue by LeoMarques101** [nekiro/TFS-1.5-Downgrades#105]
**Protocol version**
8.60

**Describe the bug**
The player:addBlessing(id) and player:hasBlessing(id) are not working well, for some reason not all blessings are being added correctly and i don't know if this is a datapack problem.

**To Reproduce**
Use the items in scripts/actions/others/blessing_charms.lua and test using scripts/actions/tools/check_bless.lua

**Expected behavior**
The correct behavior of the functions player:addBlessing(id) and player:hasBlessing(id) 

**Screenshots**
nop

**Additional context**
nop

**Comment by nekiro** [comment]
https://github.com/nekiro/TFS-1.5-Downgrades/pull/103
helps?

**Comment by LeoMarques101** [comment]
> #103 helps?

Thanks sekiro!, i will check this in the end of the day and comeback to tell if its ok

**Comment by LeoMarques101** [comment]
Working fine !!
