### ISSUE TITLE
Draw Well Bug

### ISSUE THREAD

**Issue by mirkaan** [nekiro/TFS-1.5-Downgrades#107]
**Protocol version**
7.72/8.00

When u use this item, u go to down floor.
<item fromid="1368" toid="1369" 

First Floor
![image](https://user-images.githubusercontent.com/98285577/151259901-1a20762c-1da7-4e14-998a-69f0abc80dc4.png)

Second Floor after use.
![image](https://user-images.githubusercontent.com/98285577/151259964-bd664e6f-e973-4e23-b706-fefe815cd65f.png)

**Comment by mirkaan** [comment]
To solve this just remove from actions.xml

	<action itemid="1368" script="other/teleport.lua" />
	<action itemid="1369" script="other/teleport.lua" />

**Comment by waqmaz93** [comment]
Draw wells have the same ID on real map so ise pick script to fix them.

> To solve this just remove from actions.xml
> 
> ```
> <action itemid="1368" script="other/teleport.lua" />
> <action itemid="1369" script="other/teleport.lua" />
> ```

Draw wells have the same ID on real map so ise pick script to fix them.
