### ISSUE TITLE
Ghost mode bug still not working well. Problem with cloning players

### ISSUE THREAD

**Issue by waqmaz93** [nekiro/TFS-1.5-Downgrades#108]
**Protocol version**
Tested on 7.72

**Describe the bug**
According to this thread: https://github.com/nekiro/TFS-1.5-Downgrades/issues/101
Logging out while in ghost mode and then loggin to the game and logging out being in a normal form causes copy of yourself

**To Reproduce**
1. Type /ghost on your gm account
2. logout at another player
3. login to the game again
4. your character is no longer in ghost mode and if you logout again, copy of you is created and this copy is visible only for the other players but not for you

**GIF**
![ghost mode bug](https://user-images.githubusercontent.com/45514240/151380289-2b130c24-87ee-4026-8f6c-a5a779f4f1bb.gif)

**Comment by nefrenowiec** [comment]
In tibia 8.6 when GM type ghost and logout players on screen get debug.

**Comment by nekiro** [comment]
Can't reproduce, tested with cip client

**Comment by waqmaz93** [comment]
> Can't reproduce, tested with cip client on latest branch as of today.

Confirm, I can no longer reproduce it after adding the updated version of the script. The bug was possible to reproduce with the script including "continue".
