### ISSUE TITLE
Error saying "Attempt to index a nil value"

### ISSUE THREAD

**Issue by Flyingbootsie** [nekiro/TFS-1.5-Downgrades#109]
**Protocol version**
7.72

**Describe the bug**
Hello there, I compiled the distribution like I do all others, but when I click to start the server it says "PANIC: unprotected error in call to Lua API (attempt to index a nil value)

Visualstudios directed me to this line of code in the source of luascript.cpp:

`lua_register(luaState, "isValidUID", LuaScriptInterface::luaIsValidUID);`

**To Reproduce**
Start the server(Idk I'm sorry I'm very new to making issues here on github idk what else to tell ya.)

**Expected behavior**
Server to start with other errors.

**Screenshots**

https://i.imgur.com/rad6cON.png

https://i.imgur.com/uc2NJ8U.png

**Additional context**
![2022-02-02 12_19_53- 7 60-7 72  Latest forgottenserver 1 3  Clean downport  _ OTLand](https://user-images.githubusercontent.com/87466720/152145018-c1d8a52f-6019-435d-9cac-ec9fa6efbd8f.png)
![2022-02-02 12_23_14-theforgottenserver (Debugging) - Microsoft Visual Studio](https://user-images.githubusercontent.com/87466720/152145044-6cc153d1-ab94-4f5f-a05b-20970b2cdfe2.png)

**Comment by Znote** [comment]
Are you using `isValidUID` anywhere in your datapack?

**Comment by Flyingbootsie** [comment]
I haven't changed the datapack at all, I just downloaded the downgrade from github and fired it off to test it, nothing was changed except config.lua.

**Comment by Znote** [comment]
Hmm, thats odd. I dont think the default data is any good, but I suppose it should at least be able to run.

**Comment by Flyingbootsie** [comment]
So I just downloaded both the 8.0 downgrade and the 8.6 downgrade as well and tried to compile those and they all have the same issue, is there just something wrong with how I compile it or my library?

**Comment by nekiro** [comment]
I used today these engines and they launch just fine, so there is something wrong with your compile.

**Comment by Flyingbootsie** [comment]
Alright, I'll see if I can reinstall everything. Thanks. :)

**Comment by Flyingbootsie** [comment]
Ok so re-installing my vcpkg solved the compilation issue, I'm so sorry for this I probably should have tried this first. I'll close the issue. Thanks again for the help from both of you! :)
