### ISSUE TITLE
Eating items into dust if inventory full

### ISSUE THREAD

**Issue by Kavuxus** [nekiro/TFS-1.5-Downgrades#112]
**Protocol version**
7.72

**Describe the bug**
While the inventory of a player is full and having the inventory of a player minimised, drag and drop any item onto the "capacity and soul display" and it will eat the item into pure dust - basically delete the item.

**Expected behavior**
Well, its supposed to either throw an error to the player in the console (or above) to notify the player that the inventory is full/there is no space.

**Comment by nekiro** [comment]
Upstream bug, report issue to tfs

**Comment by nekiro** [comment]
https://github.com/otland/forgottenserver/pull/3923
