### ISSUE TITLE
Paying house rent does not work

### ISSUE THREAD

**Issue by waqmaz93** [nekiro/TFS-1.5-Downgrades#116]
/invalid 

I am sorry the issue in invalid.
After about 3 days of trying to fix the problem I have just noticed that the bug was with world-house.xml file and its rent set to "0" so it was replacing my "rent" in database field every time I started the server.

**Comment by nekiro** [comment]
If it doesnt work, then report to upstream, this code wasnt even touched

**Comment by Znote** [comment]
I can remember having this issue in upstream, but though I broke it somehow in my PR.
<https://github.com/otland/forgottenserver/pull/2214#issuecomment-727653185>

Not sure if world-house.xml file should replace the original house price calculations, sounds like an (upstream) bug.

**Comment by EPuncker** [comment]
house price is for buying a house, rent need to be added via map editor or manually editing house.xml file

but yeah, nobody does that, maybe we should add a config we used to have at 0.4: **housePriceAsRent** = true/false

**Comment by waqmaz93** [comment]
> house price is for buying a house, rent need to be added via map editor or manually editing house.xml file
> 
> but yeah, nobody does that, maybe we should add a config we used to have at 0.4: **housePriceAsRent** = true/false

yeah, that was very good option. for someone who doesnt really know the engine, like me, its a waste of time. took me 3 days, haha

**Comment by waqmaz93** [comment]
> I can remember having this issue in upstream, but though I broke it somehow in my PR. [otland/forgottenserver#2214 (comment)](https://github.com/otland/forgottenserver/pull/2214#issuecomment-727653185)
> 
> Not sure if world-house.xml file should replace the original house price calculations, sounds like an (upstream) bug.

yeah, if you set the rent price in database and its "0" in your xml file, the database will be updated to "0"
