### ISSUE TITLE
game combat messages

### ISSUE THREAD

**Issue by emil92b** [nekiro/TFS-1.5-Downgrades#117]
**Protocol version**
7.72

**Describe the bugs**
* the combat log messages are displaying things they shouldn't
* when taking damage while having mana shield active you see strange symbols instead of numbers

**To Reproduce**
1. open 2 clients and login
2. take damage with and without mana shield and watch combat messages

**Expected behavior**
should only be able to see the damage that you take, nothing else

11:11 You lose 1 hitpoint.
11:11 You lose 1 hitpoint due to an attack by a bug.

11:11 You lose 1 mana.
11:11 You lose 1 mana blocking an attack by Nekiro.

https://github.com/nekiro/TFS-1.5-Downgrades/blob/7.72/src/game.cpp#L3990-L4300

**Screenshots**
![44444](https://user-images.githubusercontent.com/43324808/153388790-9b0ea19c-90d0-4d37-93d9-6e9ee3847fa7.png)

**Comment by nekiro** [comment]
Fixed in https://github.com/nekiro/TFS-1.5-Downgrades/commit/20ee887698b37fc1252a194e0193fd8335a755a2
