### ISSUE TITLE
[visual] combat target & area effects

### ISSUE THREAD

**Issue by emil92b** [nekiro/TFS-1.5-Downgrades#121]
**Protocol version**
7.72

**Describe the bug**
the target/area spell has their effects in wrong order for both player and monster spells

**Expected behavior**
energy wave, teleport effect should be on bottom and energy damage type on top
sudden death, mortarea effect should be on bottom and physical hit/spark/poff on top

**Screenshots**
![123](https://user-images.githubusercontent.com/43324808/155190658-f8ec19d7-ca38-4735-a718-79556baee43a.gif)

**Comment by nekiro** [comment]
lol

**Comment by emil92b** [comment]
> lol
maby you should just close this repository since you don't even care, stick to 12.x instead xD

**Comment by nekiro** [comment]
> > lol
> 
> maby you should just close this repository since you don't even care, stick to 12.x instead xD

That's not even a real issue. I fix bugs, not protocol specific things of which I don't care just like you mentioned.

**Comment by emil92b** [comment]
> That's not even a real issue. I fix bugs, not protocol specific things of which I don't care just like you mentioned.

right, well i thought you meant you don't do datapack things, and then i post one that might be source related.

> No need to close it though, maybe someone will actually "care" and fix this "issue" :)

yes you are right, i shouldn't. but this repository looks so inactive and with that "lol" response it felt pointless to even have open it to begin with.

i have been testing alot of things how they work and so on, sharing issues with repositories like this one whenever i come across one, doesn't matter if it's a critical bug or small detail, because i want there to be a free oldschool repository with matching mechanics as in old days.

> P.S good defnition of caring though. I cared enough to do this and other downgrades for you and all other community **for free**, but I see it's still not enough?

it is, and i thank you for that. i wasn't aware of what you wanted to achieve with this other than the downgrade itself.

**Comment by nekiro** [comment]
I'll mark this as an enhancement

**Comment by waqmaz93** [comment]
I try to find which part of the code is responsible for that. Does anyone if its an order of the script execution or rather some script itself
