### ISSUE TITLE
[7.72] Cannot see house owners

### ISSUE THREAD

**Issue by BrikoTV** [nekiro/TFS-1.5-Downgrades#122]
**Protocol version**
7.72

**Describe the bug**
I cannot see house owner description.

**To Reproduce**
1. Run your own server with tfs 1.5 (7.72 downgrade)
2. Add one house
3. Open server
4. Click on house doors.

**Expected behavior**
Nobody owns this house etc.

**Screenshots**
![image](https://user-images.githubusercontent.com/78261126/155858626-a7381b85-cc71-417e-95bd-2eeee625df77.png)

**Comment by BrikoTV** [comment]
> Fix your houses

How and what do you mean?

**Comment by emil92b** [comment]
press ctrl+h to see house tiles, make sure you added the tiles aswell house exit.
also right click door and click properties see if "door id" exists and match your house in the pallete, if you don't see it check items.xml in rme folder that id 1221 has `<attribute key="type" value="door"/>`

![444](https://user-images.githubusercontent.com/43324808/155862751-0e997a88-2346-471e-a916-6523653a827c.PNG)

**Comment by emil92b** [comment]
> Thanks for help man. I don't know why, but my Door ID was 0 everywhere. It fixes probem. Thanks once again!

happy to hear :) np
