### ISSUE TITLE
[visual] character list premium days

### ISSUE THREAD

**Issue by emil92b** [nekiro/TFS-1.5-Downgrades#125]
**Protocol version**
7.72

**Describe the bug**
"premium_ends_at" db value is 0, but still says you have premium account (46485 days) in character list, having days or free premium seems to display fine.

https://github.com/nekiro/TFS-1.5-Downgrades/blob/7.72/src/protocollogin.cpp#L135

**Expected behavior**
should display free account

**Comment by nekiro** [comment]
Ah yeah this is a common issue, premium_ends_at is at 0 by default just like you mentioned, which underflows the value and produces a big positive number which results in your dummy x days of premmy

**Comment by nekiro** [comment]
https://github.com/nekiro/TFS-1.5-Downgrades/commit/6f11e19f99957a3a1324a8493159d2b33944bcf1
Should help

**Comment by emil92b** [comment]
tested and works
