### ISSUE TITLE
CONST_ME_ENERGYAREA causing client crash on cipsoft client. With otclient effect is not rendered

### ISSUE THREAD

**Issue by jakub742** [nekiro/TFS-1.5-Downgrades#126]
**Protocol version**
7.72

**Describe the bug**
When i use CONST_ME_ENERGYAREA as a spell effect it doesnt work. Crash on cip client. With OTclient the dmg will work but effect wont.

**To Reproduce**
1. Edit spell.lua to use combat:setParameter(COMBAT_PARAM_EFFECT, CONST_ME_CONST_ME_ENERGYAREA) -- NOT WORKING
2. Change the effect to something else -  CONST_ME_ENERGYHIT and the spell works normally
3. I have latest pull with default items.otb and default spr dat client files for 772
4. No error shown in server console.

**Expected behavior**
An effect should appear on screen

**Screenshots**
With CONST_ME_ENERGYAREA
![image](https://user-images.githubusercontent.com/12849585/160076264-51cd29b2-b9d2-4b27-97fa-e75aef8f20fd.png)

With CONST_ME_ENERGYHIT 
![image](https://user-images.githubusercontent.com/12849585/160076457-798f0838-a4e3-4517-a4fa-3e6aa26f5c18.png)

Idk if im doing something wrong or not but other effects works fine.
Thanks.

**Comment by Silba93** [comment]
That's not an effect available in 7.72 client. 
Closest thing would be CONST_ME_TELEPORT

**Comment by jakub742** [comment]
> 

Omg thanks :D i was looking for that one 👍  my bad im closing this.
