### ISSUE TITLE
Error Server Log game.cpp

### ISSUE THREAD

**Issue by Azzertty** [nekiro/TFS-1.5-Downgrades#134]
**Protocol version**
7.72/8.00/8.60

**Describe the bug**
**When a monster or player uses health magic, the information does not appear in the server log.**

![HEAL MONSTER](https://user-images.githubusercontent.com/105072241/167180468-487c4533-24b7-4934-acb0-09668d9d4f43.JPG)

**Comment by mano368** [comment]
Changed anything? Here works fine

**Comment by Azzertty** [comment]
> Changed anything? Here works fine

Solved

**Comment by nekiro** [comment]
If you need help use forum and not issues. Especially when you run custom code.
