### ISSUE TITLE
Possible error with the player's direction when using `Creature.teleportTo`

### ISSUE THREAD

**Issue by MillhioreBT** [nekiro/TFS-1.5-Downgrades#33]
**Protocol version**
8.60

**Describe the bug**
[TFS Oficial PR 2133](https://github.com/otland/forgottenserver/pull/2133)
I haven't personally tested this yet, but I think this could cause strange behavior when teleporting from one place to another

**To Reproduce**
1. Add in yours scripts: `data/scripts/test.lua`
```lua
local talk = TalkAction("!tt")

function talk.onSay(player, words, param, type)
    local position = player:getPosition()
    position:getNextPosition(player:getDirection(), 1)
    player:teleportTo(position, true)
    return false
end

talk:register()
```

2. Execute the talkaction: `!tt`
3. Then observe how the character after each step always ends up facing north

**Expected behavior**
After each move the character should be looking towards the correct direction

**Comment by nekiro** [comment]
How is this related to this downgrade?

**Comment by MillhioreBT** [comment]
I have not tried it yet, but I leave it here so that someone else can check it, it is that I recently fixed this problem in one of your degraded engines but I'm not sure if it was this degradation, anyway, as soon as I find how to test it I'll let you know, I just wanted to leave this comment so that later I don't forget
