### ISSUE TITLE
Spell damage/healing etc.. calculation wrong for 7.72

### ISSUE THREAD

**Issue by dnvd** [nekiro/TFS-1.5-Downgrades#45]
**Protocol version**
7.72

**Describe the bug**
As stated in the description of this project the calculation for pretty much all spells are wrong for 7.72.
I've started looking at this project: [https://github.com/peonso/tibialegacyserver](https://github.com/peonso/tibialegacyserver)
which seems to provide better values for 7.72 even though I'm very unsure if these are 100% correct.
Might be a good start to look through this?

**To Reproduce**
Heal yourself with UH, shoot SD etc...

**Expected behavior**
Damage, healing etc.. values should be closer to 7.72

**Comment by nekiro** [comment]
Read readme in root of the repository again.

**Comment by dnvd** [comment]
Is there a reason as to why?
Seems to me that the better option would be to fix it once here instead of using obvious wrong values that everyone have to fix themselves? :)

**Comment by nekiro** [comment]
> Is there a reason as to why?
> Seems to me that the better option would be to fix it once here instead of using obvious wrong values that everyone have to fix themselves? :)

Yes obviously, though it's not the main aim with this downgrade. This is a base for people to start working on. I have no willing to research and fix these formulae. I accept help though, so contribution is very welcome. If you wish to help submit a pull request just make sure you use the template.

**Comment by dnvd** [comment]
Ok, I've done some changes on my side for now. Some further tweaking will be required for sure.
I'll do a PR when I'm happy with the result.

**Comment by Znote** [comment]
What if you want downgraded protocol, but with modern formulas?
Old formulas are usually modified for a reason, etc old UE is just broken and make sorcerers OP in high level. 
I would perhaps make a branch, `7.72-formulas` that people can merge in, if they want to use authentic formulas.

**Comment by dnvd** [comment]
While I disagree that there will be a use case for using the new formulas for 7.72. Imo, WAY too much has changed for it to even make sense. I mean, try to use an UH rune for the formulas currently used as a knight. **There is no way this is gonna be used.**
Most people that play version 7.72 want the old experience even though things are unbalanced.

However, I do agree that some people may disagree on the correct formulas for 7.72. You also have a good point that maintaining protocol compatibility will probably be easier this way.

**Comment by nekiro** [comment]
There is simply no clear indication which formula is correct, so I left it to the developers that will use this as a base to find and create their own formulae.

**Comment by dnvd** [comment]
So how should we structure this?

We have 3 choices from my perspective:
1. The community makes an effort to agree on one set of formulas that will be used here. If people want to modify it to their specific needs they will have to do it on their own.
2. We create specific branches for different types of calculations which will be maintained by the community.
3. Do nothing.

**Comment by nekiro** [comment]
1 or 3.
Simply if anyone cares submit a pull request and I will review it other than that wrong formula stay. I believe that people should at least put some effort into their servers instead of getting download and run server to host it.
Also I do it for free and in my free time, so keep that in mind.

**Comment by Silba93** [comment]
I agree that it should be up to each individual developer, this isn't released as a cip clone project it's released as a base and has no obligation to provide accurate formulas for spells just as it has no obligation to creature accurate monsters.
OTHire and Tibia legacy server and Nostalrius are quite accurate but afaik have inconsistencies that would lead to a developer researching and modifying formulas anyway and since there's so few spells in 7.72 this is not a big task for them.
