### ISSUE TITLE
Pick can be used on too many tiles?

### ISSUE THREAD

**Issue by dnvd** [nekiro/TFS-1.5-Downgrades#51]
**Protocol version**
7.72

**Describe the bug**
I can use pick on all tiles with ID 354 and 355 (might be more).
Confirmed that it doesn't work on tiles using ID 353, 352 and 351.

**To Reproduce**
1. /i 354
2. Use pick on location
3. Hole appears

**Expected behavior**
Nothing should happen

**Screenshots**
![image](https://user-images.githubusercontent.com/88395501/128189332-5335705f-5249-4c0a-b0ac-f1b7a94f0405.png)

**Comment by nekiro** [comment]
No idea, probably just wrongly registered ids in actions.xml or revscriptsys actions.

**Comment by dnvd** [comment]
Yes.
I'm comparing the files used in this repo
https://github.com/peonso/tibialegacyserver/blob/master/server/data/actions/scripts/tools/pick.lua
with the one in this repo:
https://github.com/nekiro/TFS-1.4-Downgrades/blob/7.72/data/actions/scripts/tools/pick.lua

And there seems to be a big difference here if this is any help.

**Comment by nekiro** [comment]
As I said. I won't work on the datapack, so if you feel like making it better, submit a pull request, thanks.

**Comment by dnvd** [comment]
Ok, thank you for your response.
Maybe you want to keep the downgrade clean from these types of modifications though?
I'm guessing that modifications in these files for the 7.72 branch could cause problems when merging from upstream later down the line?

**Comment by nekiro** [comment]
I don't think editing lua scripts, would be any kind of hassle when merging upstream, because what we do is cherry-pick relevant commits and just solve conflicts if any.
