### ISSUE TITLE
Torches doesn't work

### ISSUE THREAD

**Issue by dnvd** [nekiro/TFS-1.5-Downgrades#59]
**Protocol version**
7.72

**Describe the bug**
Torches doesn't work

**To Reproduce**
1. /m torch
2. Try using the torch
3. "You cannot use this object"

**Expected behavior**
Torch should be lit

**Comment by nekiro** [comment]
Fix the action script if there is any.

**Comment by Znote** [comment]
Works fine in 8.60 branch
You can probably just add it to your 7.72 branch and remove the itemids thats not supported in protocol. 

https://github.com/nekiro/TFS-1.4-Downgrades/blob/d37f74a6cd1a201656f4ea3cbd8d9dacd2ffe4f8/data/actions/actions.xml#L35

https://github.com/nekiro/TFS-1.4-Downgrades/blob/d37f74a6cd1a201656f4ea3cbd8d9dacd2ffe4f8/data/actions/scripts/other/decayto.lua#L1-L26
