### ISSUE TITLE
CTRL+R Issue with Tibia 8.6

### ISSUE THREAD

**Issue by Dzanar** [nekiro/TFS-1.5-Downgrades#63]
**Protocol version**
8.60

**Describe the bug**
CTRL+R Rule Violation not working. Report was not been sent to Gamemaster.

**To Reproduce**
1. CTRL+R and write soething to report to Gamemaster

**Expected behavior**
A Report was been sent to the Gamemaster.

**Screenshots**

**Additional context**

**Comment by Emilianenko** [comment]
https://github.com/Emilianenko/optimized_forgottenserver-1/commit/5640e438f6f02959b038a620f526f53ad322fbe8

**Comment by Hayvosh** [comment]
This would indeed be a nice feature, actually just noticed it myself yesterday that this wasn't working. (7.72)
