### ISSUE TITLE
Life Fluid not working on hotkey

### ISSUE THREAD

**Issue by paola92** [nekiro/TFS-1.5-Downgrades#73]
**Protocol version**
8.00

**Describe the bug**
Life Fluid not working on hotkey. Mana fluid is ok.

**To Reproduce**
1. add life fluid to hotkey on yourself
2. try use

**Expected behavior**
should use life fluid

**Screenshots**
simple to reproduce

**Additional context**
simple to reproduce

**Comment by gesior** [comment]
Client does not know, if in bottle is 'blood' or 'life fluid'. From client side both have 'color red' (id 5).
Some part of OTS communication with client is bugged or it was badly designed by Tibia client authors.
Anyway, you can trick it by replacing:
```
const uint8_t reverseFluidMap[] = {
	FLUID_EMPTY,
	FLUID_WATER,
	FLUID_MANA,
	FLUID_BEER,
	FLUID_EMPTY,
	FLUID_BLOOD,
	FLUID_SLIME,
	FLUID_EMPTY,
	FLUID_LEMONADE,
	FLUID_MILK,
};
```
with:
```
const uint8_t reverseFluidMap[] = {
	FLUID_EMPTY,
	FLUID_WATER,
	FLUID_MANA,
	FLUID_BEER,
	FLUID_EMPTY,
	FLUID_LIFE,  // <<<< -----
	FLUID_SLIME,
	FLUID_EMPTY,
	FLUID_LEMONADE,
	FLUID_MILK,
};
```
then server will allow to use 'drink lifefuild' hotkey, but block 'drink blood' hotkey. Using blood by clicking 'Use with..' it will still work.
