### ISSUE TITLE
Real 8.0 code

### ISSUE THREAD

**Issue by gesior** [nekiro/TFS-1.5-Downgrades#78]
I did not use bug report format, because I'm not reporting bug. I will make PRs referring to this Issue.

In 8.0 version there is a code for many thing that did not exist in 8.0.
- 'earth' damage was 'poison' in 8.0
- 'death', 'holy' and 'ice' damage did not exist
- element damage in weapons did not exist (like 35 physical + 3 fire)
- CONST_ME and CONST_ANI contains a lot of animations that did not exist in 8.0 times, which make Tibia client crash
- - using 'wand of decay' make client crash - try to deal 'death damage' and send 'death damage animation', which did not exist in 8.0

**Comment by nekiro** [comment]
Datapack is not included with this downgrade, that's why you see stuff like elemental damage, it's there in the code, so people can easily adjust or use tfs newer protocol code without problems. It's left for compatibility. I don't plan to change that nor fix datapack, as it's protocol downgrade, not download and run server.

**Comment by kontownik** [comment]
Hey, I saw the same problem on another distro called eAthena (Ragnarok Online), they used `ifndef` for that. So the idea is to change the packet version (protocol for Tibia) on the compilation level, this way the server will never send a packet that is not supposed to be used for the client (Gęsior point). I hope that will make a lot of warnings or crashes during the distro launch, making people clean the data pack by themselves (Nekiro's point).

Not sure how to fix LUA part...

btw. Isn't swimming.lua breaking a single source of truth as it's redefining the conditions on script level?

Code examples:
https://github.com/eathena/eathena/blob/master/src/common/mmo.h
