### ISSUE TITLE
Client 7.72 debug while fighting monsters.

### ISSUE THREAD

**Issue by waqmaz93** [nekiro/TFS-1.5-Downgrades#81]
I get crash all the time while fighting a tarantula.
Here image of crash and tarantula.xml file:

https://imgur.com/cSVpdiE
https://i.imgur.com/cSVpdiE.png

tarantula.xml file:
`<?xml version="1.0" encoding="UTF-8"?>
<monster name="Tarantula" nameDescription="a tarantula" race="venom" experience="120" speed="214" manacost="485">
	<health now="225" max="225" />
	<look type="219" corpse="6060" />
	<targetchange interval="4000" chance="10" />
	<flags>
		<flag summonable="1" />
		<flag attackable="1" />
		<flag hostile="1" />
		<flag illusionable="1" />
		<flag convinceable="1" />
		<flag pushable="0" />
		<flag canpushitems="1" />
		<flag canpushcreatures="0" />
		<flag targetdistance="1" />
		<flag staticattack="90" />
		<flag runonhealth="0" />
		<flag canwalkonenergy="0" />
		<flag canwalkonfire="0" />
	</flags>
	<attacks>
		<attack name="melee" interval="2000" min="0" max="-90" poison="40" />
		<attack name="earth" interval="2000" chance="10" target="1" radius="1" range="1">
			<attribute key="shootEffect" value="poison" />
			<attribute key="areaEffect" value="carniphila" />
		</attack>
	</attacks>
	<defenses armor="20" defense="20">
		<defense name="speed" interval="2000" chance="15" speedchange="220" duration="5000">
			<attribute key="areaEffect" value="redshimmer" />
		</defense>
	</defenses>
	
	<loot>
		<item name="gold coin" countmax="40" chance="79000" />
		<item name="brass legs" chance="3050" />
		<item name="plate shield" chance="2000" />
		<item name="steel helmet" chance="990" />
		<item id="2169" chance="120" />
	</loot>
</monster>
`

I will be posting more if I discover why it crashes. I will have a look into source tomorrow.

/edit ive just found someone had the same problem:
https://otland.net/threads/client-7-72-crash-on-hunt.275190/

/edit this happens when monster just hits you. it happens randomly

**Comment by mattyx14** [comment]
value="carniphila

**Comment by nekiro** [comment]
That's not a crash, but client debug. Likely, because you use wrong datapack or the one from downgrade (monsters arent downgraded), datapack is not included with this release. Fix your monster attacks, it debugs probably due to missing effects from newer tibia.
