### ISSUE TITLE
Saving depot items

### ISSUE THREAD

**Issue by nefrenowiec** [nekiro/TFS-1.5-Downgrades#83]
**Protocol version**
8.60

**Describe the bug**
Again bug with saving items in depot, locker. This fix doesn't work: 
https://github.com/nekiro/TFS-1.4-Downgrades/commit/fad6e9eb10cb5991b8df963a2ee6ffeffda93120 
Now items still dont save in container and if i put new item to bp and relog this item disappears. No error is displayed on the console.
**To Reproduce**
1. Login to game
2. Put backpack in locker
3. Put 2 items to backpack in locker
4. Relog
5. change places of these 2 items
6. relog and items dont save
7. Put other item to bp and relog = new item disappear

**Expected behavior**

**Screenshots**
https://streamable.com/1n92ng

**Additional context**

**Comment by nekiro** [comment]
https://github.com/nekiro/TFS-1.4-Downgrades/commit/4f6a09d16dac8444d8142f3f8f05d06c31812eaa

**Comment by nefrenowiec** [comment]
> [4f6a09d](https://github.com/nekiro/TFS-1.4-Downgrades/commit/4f6a09d16dac8444d8142f3f8f05d06c31812eaa)

I am using 8.6 version I made this changes ^ and now I have a compilation error: `/home/ots/src/iologindata.cpp:568:6: error: no declaration matches ‘bool IOLoginData::saveDepotItems(const Player*, const ItemBlockList                  &, DBInsert&, PropWriteStream&)’
  568 | bool IOLoginData::saveDepotItems(const Player* player, const ItemBlockList& itemList, DBInsert& query_insert, PropWriteStream&                   propWriteStream)
      |      ^~~~~~~~~~~
/home/ots/src/iologindata.cpp:568:6: note: no functions named ‘bool IOLoginData::saveDepotItems(const Player*, const ItemBlockList&, DB                  Insert&, PropWriteStream&)’
In file included from /home/ots/src/iologindata.cpp:22:
/home/ots/src/iologindata.h:29:7: note: ‘class IOLoginData’ defined here
   29 | class IOLoginData
      |       ^~~~~~~~~~~
make[2]: *** [CMakeFiles/tfs.dir/build.make:499: CMakeFiles/tfs.dir/src/iologindata.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:125: CMakeFiles/tfs.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
`

**Comment by nekiro** [comment]
You didnt copy right.

**Comment by nefrenowiec** [comment]
@nekiro 
So I did an experiment and I downloaded your 7.72 branch and I tried to compile it. As a result, the same error occurred.
![image](https://user-images.githubusercontent.com/94572294/145072650-13e2c16d-e336-4d3f-a236-a4b17b86051b.png)

**Comment by waqmaz93** [comment]
> 

Upload your iologindata.cpp and .h files

**Comment by nefrenowiec** [comment]
> > 
> 
> Upload your iologindata.cpp and .h files because for me everything works fine

Hmm I do not know what's going on moments ago I downloaded 7.72 from github and i got errors. :o

**Comment by waqmaz93** [comment]
Coudl you be more clear? please

**Comment by nefrenowiec** [comment]
> Coudl you be more clear? please

https://github.com/nekiro/TFS-1.4-Downgrades/tree/7.72 
I downloaded it and I tried to compile it but i got errors (screen on previous post).

**Comment by nekiro** [comment]
https://github.com/nekiro/TFS-1.4-Downgrades/commit/bd5186be97190d403922602d992f6aa34b27603e

**Comment by nefrenowiec** [comment]
I dont know I made it all and still the same error

**Comment by nekiro** [comment]
Apply this too:
https://github.com/nekiro/TFS-1.4-Downgrades/commit/3eef08ec911ddeeeecbc8fbef85d517c454ac16a

**Comment by nefrenowiec** [comment]
> Apply this too: [3eef08e](https://github.com/nekiro/TFS-1.4-Downgrades/commit/3eef08ec911ddeeeecbc8fbef85d517c454ac16a)
now it can be compiled, but there is a saving error all the time like here:
https://streamable.com/1n92ng

**Comment by waqmaz93** [comment]
> > Apply this too: [3eef08e](https://github.com/nekiro/TFS-1.4-Downgrades/commit/3eef08ec911ddeeeecbc8fbef85d517c454ac16a)
> 
> now it can be compiled, but there is a saving error all the time like here: https://streamable.com/1n92ng

It works for me. Try on new client and write your code carefully. + Send me your database.

**Comment by nefrenowiec** [comment]
> 

What you mean new client. Bro i downloaded all files from Nekiro github and compile it and it doesn't work

**Comment by nekiro** [comment]
Should be ultimately fixed in https://github.com/nekiro/TFS-1.5-Downgrades/commit/de2815e13fda58c9072828a79b670c2dbb326377
