### ISSUE TITLE
Beds not working

### ISSUE THREAD

**Issue by Hayvosh** [nekiro/TFS-1.5-Downgrades#89]
**Protocol version**
7.72

**Describe the bug**
When you are ingame and own a house, right clicking the bed does not make the character go to sleep and logout.
There is nothing happening, no errors in serverlog or client log.
Just no interraction what so ever, this worked in 1.4 downport.

**To Reproduce**
1. Go to a player owned house with the character that owns the house ( or a character that is invited )
2. Rigtclick the bed to sleep/logout

**Expected behavior**
Character should be put to sleep in the bed and player is logged out.

**Comment by Hayvosh** [comment]
Ok, after some digging and comparing old vs. new code from TFS 1.4 and TFS 1.5 from Nekiros 7.72 branch I found the issue.
In Actions.cpp on line 345/355 there was a line missing "bed>sleep(player);".
This was present in the 1.4 source but missing in the 1.5, so I added it back and it works again!

In actions.cpp on line 353-356

        if (bed->trySleep(player)) {
            player->setBedItem(bed);
            bed->sleep(player); //Added this line back (missing in TFS 1.5)
              //g_game.sendOfflineTrainingDialog(player);

**Comment by nekiro** [comment]
Fixed in https://github.com/nekiro/TFS-1.5-Downgrades/pull/91
