### ISSUE TITLE
Erro RL Map 8.60

### ISSUE THREAD

**Issue by Nanduzenh0** [nekiro/TFS-1.5-Downgrades#90]
when I put my global map it debugs and when soon OTC does not show some parts of the map. I've tried it with other maps and the same thing happens. I've already tried to exchange other items.otb and nothing to fix. Does anyone know what it can be and how to fix it?
![erro tfs 1 5](https://user-images.githubusercontent.com/96787904/147587461-705a319f-9fab-4d12-bc8b-97c156a5a44f.JPG)

**Comment by nekiro** [comment]
I think that's question for support board on otland

**Comment by Nanduzenh0** [comment]
> 

the problem only occurs with this TFS

**Comment by Nanduzenh0** [comment]
> I think that's question for support board on otland

the problem only occurs with this TFS

**Comment by nekiro** [comment]
No shit man, the thing is, the problem might be wrong items.otb, wrong map or wrong client files. I have no idea what datapack you use nor what mapa you use, I can't help you nor I have time. Use support board on otland.
