### ISSUE TITLE
Standing on monster's spawn on your god account makes a copy of you and lags the client

### ISSUE THREAD

**Issue by waqmaz93** [nekiro/TFS-1.5-Downgrades#93]
**Protocol version**
7.72 - tested on 7.72 version only

**Describe the bug**
When you stand on a monster's spawn position on your god account and monster spawns then if you press ctrl + any arrow key (sometimes any key does not have to be pressed), a copy of you is created.

**To Reproduce**

0. Make a monster with the fastest possible spawn time of 10 seconds to easier reproduce the bug,
1. Login on your god account,
2. Kill that monster,
3. Stand exactly on his spawn place,
4. Wait for the monster to appear,
5. Press any arrow key to move your character,
6. If copy of you has not appeared yet, try ctrl + any arrow key - a copy of you should appear.

**Expected behavior**
A copy of you should not appear

**Screenshots**
![image](https://user-images.githubusercontent.com/45514240/148377972-2b0eeabe-b19f-4e69-a58e-e19af16c2ab8.png)
** GIF **
![critical bug](https://user-images.githubusercontent.com/45514240/148378120-5c1c85e5-7407-4bd9-8c6c-2d93502660ae.gif)

**Additional context**
I am not sure it is upstream bug or Nekiro 1.5 downgraded version

**Comment by nekiro** [comment]
Probably creating creature into player position is broken.
Execute:
```Game.createMonster("wolf", player:getPosition(), false, true)```
and let me know if it happens too.

**Comment by waqmaz93** [comment]
I have just tested with player. 
If you log with your God account on the place where normal player stands, the copy of you appears aswell.
** GID: **
![critical bug gm](https://user-images.githubusercontent.com/45514240/148379948-55b42229-a347-4c22-8802-9f6cfe82bdc9.gif)

**Comment by nekiro** [comment]
Most likely stackpos issue as always. I'll take a look when I can

**Comment by celohere** [comment]
https://github.com/nekiro/TFS-1.5-Downgrades/blob/7.72/src/tile.cpp#L1417
https://github.com/nekiro/TFS-1.5-Downgrades/blob/7.72/src/tile.cpp#L838

**Comment by waqmaz93** [comment]
> https://github.com/nekiro/TFS-1.5-Downgrades/blob/7.72/src/tile.cpp#L1417 https://github.com/nekiro/TFS-1.5-Downgrades/blob/7.72/src/tile.cpp#L838 Just change the line 838 from : `creatures->insert(creatures->end(), creature);` to: `creatures->insert(creatures->begin(), creature);`

I've jsut compiled your advice and the problem still exists. Nothing didn't change at all.

**Comment by nekiro** [comment]
Fixed in https://github.com/nekiro/TFS-1.5-Downgrades/commit/226e937c27629e7debff2ebb02c0af8edb9559f7
