### ISSUE TITLE
Client debug again

### ISSUE THREAD

**Issue by nefrenowiec** [nekiro/TFS-1.5-Downgrades#96]
**Protocol version**
8.60

**Describe the bug**
After this changes: https://github.com/nekiro/TFS-1.5-Downgrades/commit/744a2b84b3554714e46c17fdbb9b000c874402a8 
https://github.com/nekiro/TFS-1.5-Downgrades/commit/451007ae2ccb891375ac0ea93fd066c7410a6191
client get debug when you open backpack with items inside

**To Reproduce**
1. Create backpack
2. Put vial to backpack
3. Try open backpack
4. Get debug

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by nekiro** [comment]
![devenv_1ISiU2eMdX](https://user-images.githubusercontent.com/14142246/149204657-6df42742-61d9-4fb0-acd8-cbe7e9cf4cba.gif)

**Comment by nefrenowiec** [comment]
@nekiro Sorry I edited main post Look at step 2.

**Comment by nekiro** [comment]
![Tibia_9QdquhfB07](https://user-images.githubusercontent.com/14142246/149204954-6d41cba1-f1ec-4b77-a0ab-458978eca437.gif)

**Comment by nefrenowiec** [comment]
Ok that was my mistake after trying to fix it myself. But look in your server the jug and vial again dont work? Is this error only with me? 
https://gyazo.com/be858ebd52796c7b2ea605f988149493

**Comment by nekiro** [comment]
> Author

Cipsoft does not push fluid flag for jug, so it's not a container from client side (dat file), if you want it to be container add fluidcontainer flag in xml

**Comment by nefrenowiec** [comment]
Hm jug ok but vials dont work too (?)

**Comment by nekiro** [comment]
same thing?

**Comment by waqmaz93** [comment]
Works fine for me.
